### ISSUE TITLE
[1.18.2] Crash when using Shaders while on other planets.

### ISSUE THREAD

**Issue by ConqAra** [terrarium-earth/Ad-Astra#35] opened 2022-10-31 08:39 UTC
(Tested on Mars) When traveling to, and landing on, mars you will crash if you have shaders (tested with BSL Shaders) on. 

[Crashlog ](https://paste.ee/p/jl9B1) starting with the Error and list of mods in the pack just in case it's not just iris.

**Comment by AlexNijjar** [comment] 2022-10-31 08:49
It's extremely difficult for mod devs to diagnose issues caused by optimization and shader mods, such as sodium + iris. I can't tell if this is an Ad Astra issue or Iris issue, but nevertheless, I'd recommend reporting it on Iris's GitHub. You can disable shaders on planets for now, until it's fixed.

**Comment by parzivail** [comment] 2022-11-01 20:46
Does Ad Astra make a mixin for `ItemStack` that could cause `ItemStack::getItem` to return null (e.g. by setting the value of the stack to null without updating `empty`)? if it does, that would cause this issue.

**Comment by AlexNijjar** [comment] 2022-11-02 14:19
There's no `ItemStack` mixin and as far as I am aware, I don't set any stacks to null. Only thing I've seen that might be causing issues is [this](https://github.com/terrarium-earth/Ad-Astra/blob/69a8895d5f155b65665f5719dfd37210245722f8/common/src/main/java/earth/terrarium/ad_astra/mixin/client/HeldItemRendererMixin.java#L21)

**Comment by AlexNijjar** [comment] 2022-11-17 03:53
Another shader issue #26 was recently fixed on the latest 1.19.2 version and I wonder if it correlates with this at all. Can you try on the latest version and see if it still crashes?

**Comment by IMS212** [comment] 2022-11-17 05:27
This is an issue in Iris that we’ve fixed in 1.4.1, releasing soon.

(It did not check for an invalid item.)

**Comment by AlexNijjar** [comment] 2022-11-17 05:34
Great to hear that it's fixed

**Closed as completed by AlexNijjar** 2022-11-17 05:34 UTC
Labels: bug
