### ISSUE TITLE
[Bug]: Jet Suits In Multiplayer Are Linked 

### ISSUE THREAD

**Issue by Thalonias** [terrarium-earth/Ad-Astra#229] opened 2023-03-08 20:05 UTC
### Bug Description

If 2 players have a Jet Suit, it will effect how the Jet Suit handles if both player are next to each other.

If only 1 player is flying with the suit, the player flying won't take damage while hitting a wall and can't fly through 1 block tall gaps. 

If 2 players are flying next to each other and one stops, the player that stops using the jet suit glides like they have an elytra on.

### How to Reproduce?

2 players need a Jet suit and have to be near each other.

If only 1 person is flying, the suit won't function right for the person flying.

### Expected Behavior

The Jet Suit should damage me when I slam my face into a wall if a 2nd player has a Jet Suit on near me.

### Version

ad_astra-forge-1.19.2-1.12.4.jar

### Mod Loader Version

1.19.2 - 43.2.0

### Mod Loader

Forge

### Logs or additional context

08.03 19:41:58 [Server] Server thread/WARN Thal moved wrongly!
08.03 19:42:02 [Server] Server thread/WARN Thal moved wrongly!
08.03 19:42:08 [Server] Server thread/WARN Dis moved wrongly!
08.03 19:42:09 [Server] Server thread/WARN Dis moved wrongly!

**Comment by AlexNijjar** [comment] 2023-03-09 20:24
duplicate of #212

**Closed as completed by AlexNijjar** 2023-03-09 20:24 UTC
Labels: bug, duplicate
