### ISSUE TITLE
crash whenever looking at water pump

### ISSUE THREAD

**Issue by DeRp-MaSte5** [terrarium-earth/Ad-Astra#6] opened 2022-08-20 02:36 UTC
[crash-2022-08-19_22.29.33-client.txt](https://github.com/AlexNijjar/Ad-Astra-Fabric/files/9386066/crash-2022-08-19_22.29.33-client.txt)
as you can see from the crash log, the item causing the crash is a water pump, and that's literally the only mod that includes a water pump, also if you try to get the same crash using roughly enough items, it'll tell you that it's coming from Ad Astra.

**Comment by Bunny-Proxima** [comment] 2022-08-20 02:49
Where were you when this crash happened?

**Comment by AlexNijjar** [comment] 2022-08-20 03:04
Does it have anything to do with the Corners mod? Have you tried in the overworld?

**Comment by DeRp-MaSte5** [comment] 2022-08-20 03:16
i havent even touched the corners mod

**Comment by DeRp-MaSte5** [comment] 2022-08-20 03:16
i was in both the nether and the overworld and they both crash then

**Comment by DeRp-MaSte5** [comment] 2022-08-20 03:17
doesnt matter if you are on a server or not, it happens on my server and a singleplayer world

**Comment by Aulluna** [comment] 2022-08-20 09:20
> i havent even touched the corners mod

But according to the report , the crash was caused by a mod called corner , even if u didnt touch it, having it installed is enough to cause incompatiblity issues , try to get rid of it and see what happens

EDIT :
![image](https://user-images.githubusercontent.com/76559595/185738860-ab254c9f-60d6-4fff-a72f-24ac4e2558d2.png)
from the mod page .

**Comment by Aulluna** [comment] 2022-09-10 10:49
@AlexNijjar You should probably close this issue , since it is corners mod that is causing the crash not ad astra

**Comment by AlexNijjar** [comment] 2022-09-26 05:33
I haven't checked issues in a while lmao.

**Closed as completed by AlexNijjar** 2022-09-26 05:33 UTC
Labels: bug
