### ISSUE TITLE
[Bug]:  Clouds are spawning in 1.20.1 on planets when rubidium is installed

### ISSUE THREAD

**Issue by zachsai** [terrarium-earth/Ad-Astra#323] opened 2023-07-08 04:25 UTC
### Bug Description

![image](https://github.com/terrarium-earth/Ad-Astra/assets/63996164/b272d42b-d319-45de-9b99-0b5c65b68b28)

### How to Reproduce?

rubidium + ad astra, go to planet

### Expected Behavior

no clouds

### Version

1.15.1

### Mod Loader Version

47.0.45

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Twigdev** [comment] 2023-07-12 16:39
Same in forge 1.19.2 with Oculus installed

**Comment by AlexNijjar** [comment] 2023-07-14 12:54
this is a duplicate of your own issue lol #282. I don't think I can really do anything about it and I believe sodium doesn't have this issue so it's probably on their end

**Closed as not planned by AlexNijjar** 2023-07-14 12:54 UTC
Labels: bug
