### ISSUE TITLE
[Bug]: cables not working and power not working either 

### ISSUE THREAD

**Issue by leostudiosTM** [terrarium-earth/Ad-Astra#103] opened 2022-12-19 19:13 UTC
### Bug Description

Was this supposed to be normal?
![Screenshot_6](https://user-images.githubusercontent.com/107581514/208501638-b7cc9a26-8ff6-4432-b2a1-88b85f7eea8b.png)
even when i put the coal generator next to it it does not transfer energy

### Expected Behavior

the cable connecting with the machines or the generator transferring the power to the compressor

### Version

1.11.9

### Mod Loader Version

1.19.2-43.1.52

### Mod Loader

Forge

### Logs or additional context

I'm using some mods maybe something that is giving incompatibility

**Comment by AlexNijjar** [comment] 2022-12-23 10:11
<img width="1440" alt="Screenshot 2022-12-23 at 4 10 06 AM" src="https://user-images.githubusercontent.com/61668546/209316927-ba7c9d5f-0f4b-4e0d-8e32-85d877d3efd2.png">
Weird, I can't reproduce it. It's probably those mods then

**Comment by leostudiosTM** [comment] 2023-01-02 19:24
> <img alt="Screenshot 2022-12-23 at 4 10 06 AM" width="1440" src="https://user-images.githubusercontent.com/61668546/209316927-ba7c9d5f-0f4b-4e0d-8e32-85d877d3efd2.png">
> 
> Weird, I can't reproduce it. It's probably those mods then

I tried without mods too same thing

**Comment by NitroPlayz** [comment] 2023-01-05 16:58
same issue here power is not transferring between blocks

**Comment by RatFat** [comment] 2023-01-08 21:09
> ### Bug Description
> Was this supposed to be normal? ![Screenshot_6](https://user-images.githubusercontent.com/107581514/208501638-b7cc9a26-8ff6-4432-b2a1-88b85f7eea8b.png) even when i put the coal generator next to it it does not transfer energy
> 
> ### How to Reproduce?
> _No response_
> 
> ### Expected Behavior
> the cable connecting with the machines or the generator transferring the power to the compressor
> 
> ### Version
> 1.11.9
> 
> ### Mod Loader Version
> 1.19.2-43.1.52
> 
> ### Mod Loader
> Forge
> 
> ### Logs or additional context
> I'm using some mods maybe something that is giving incompatibility

Hey there! I have the same issue, did you found the solution?

**Comment by NitroPlayz** [comment] 2023-01-12 17:02
> ### Bug Description
> Was this supposed to be normal? ![Screenshot_6](https://user-images.githubusercontent.com/107581514/208501638-b7cc9a26-8ff6-4432-b2a1-88b85f7eea8b.png) even when i put the coal generator next to it it does not transfer energy
> 
> ### How to Reproduce?
> _No response_
> 
> ### Expected Behavior
> the cable connecting with the machines or the generator transferring the power to the compressor
> 
> ### Version
> 1.11.9
> 
> ### Mod Loader Version
> 1.19.2-43.1.52
> 
> ### Mod Loader
> Forge
> 
> ### Logs or additional context
> I'm using some mods maybe something that is giving incompatibility

Hello there I've identified the issue! After some looking around I found out that having Optifine installed breaks the power and the cables. After uninstalling Optifine the issue shouldn't persist any longer! (this is likely due to Optifine changing block interactions)

**Comment by LordByronV** [comment] 2023-01-31 16:59
Removing Optifine isn’t really a solution, it’s needed for performance enhancements for many people. 

I’m having this same issue (cables won’t power things, even when I force connect them using the wrench), I also don’t think fluid pipes are working either. Any way for this to be fixed? It’s preventing me from progressing in the mod. 

UPDATE: This can be solved by running your world on a server! Don’t install optifine on the server, but you can still have it locally. Since the server handles the ad Astra pipes and cables they work fine, as it doesn’t have optifine! Tested and working fully!

**Closed as completed** 2023-02-07 11:27 UTC
Labels: bug
