### ISSUE TITLE
1.19.2 Client Crashed when teleporting to other planets

### ISSUE THREAD

**Issue by ColdTearsYY** [terrarium-earth/Ad-Astra#26] opened 2022-10-06 08:25 UTC
EXCEPTION_ACCESS_VIOLATION (0xc0000005)
log: https://paste.ubuntu.com/p/jMRM6rBg9j/
latest.log: https://paste.ubuntu.com/p/SHTT6nTRh2/
mod list: https://paste.ubuntu.com/p/Rtd5v4Pbpt/

**Comment by maximumpower55** [comment] 2022-11-11 04:17
Bump. this is caused by this line https://github.com/terrarium-earth/Ad-Astra/blob/1.19/common/src/main/java/earth/terrarium/ad_astra/client/dimension/rendering/SkyUtil.java#L50 and the crash happens on Nvidia also not just AMD, this makes the mod literally unplayable for most people

I am confused to why that line is even needed
The crash happens because that vertex buffer is trying to be rendered but it hasn't been uploaded to

**Comment by Zarepheth** [comment] 2022-11-15 02:36
Also crashing when first attempting to land on the Moon.
The game crashes to desktop, with no crash log.

These are the last few entries in the general log (I let the game idle for a couple minutes before trying to land, so log entries prior to these are probably not relevant to the crash).
```
[20:11:43] [Server thread/INFO]: Server performance level: bad
[20:11:43] [Render thread/INFO]: [CHAT] §7Hold §cSpace!
[20:11:43] [Render thread/INFO]: Stopping worker threads
[20:11:43] [Render thread/INFO]: Stopping worker threads
[20:11:43] [Render thread/INFO]: WorldRenderer reloaded ad_astra:moon
[20:11:43] [Render thread/INFO]: Started 10 worker threads
[20:11:43] [Server thread/INFO]: Zarepheth has reached the goal [One Small Step]
[20:11:43] [Server thread/INFO]: Not storing return portal because it's from ResourceKey[minecraft:dimension / minecraft:overworld] to ResourceKey[minecraft:dimension / ad_astra:moon]
[20:11:43] [Render thread/INFO]: [CHAT] Zarepheth has reached the goal [One Small Step]
```

Note: I never saw the chat messages, the game crashed before they could render.

I've added Ad Astra to my Curse Forge Overwolf Client's "Better MC [FABRIC 1.19.2 v10" modpack profile (along with many other mods).

**Comment by AlexNijjar** [comment] 2022-11-15 02:39
A new 1.19 version is coming out very soon which will hopefully fix this

**Comment by maximumpower55** [comment] 2022-11-17 03:36
Just tested
And the crash is fixed in the latest version aka <https://modrinth.com/mod/ad-astra/version/1.11.2-FABRIC>

**Closed as completed** 2022-11-17 03:39 UTC
Labels: bug

**Comment by AlexNijjar** [comment] 2022-11-17 03:42
Great. The problem was that Minecraft changed something in their 1.19 rendering code, but Ad Astra was still using the 1.18.2 version of that code.
