### ISSUE TITLE
[Bug]: Incompatible with keybind collision fixing mods

### ISSUE THREAD

**Issue by jakeismyname** [terrarium-earth/Ad-Astra#74] opened 2022-11-29 16:01 UTC
### Bug Description

Unable to launch rockets while using mods like [Amecs](https://www.curseforge.com/minecraft/mc-mods/amecs) or [Keybind Fix](https://www.curseforge.com/minecraft/mc-mods/keybind-fix). Tested on Fabric and Quilt.

### How to Reproduce?

1. Install either Amecs or Keybind Fix alongside Ad Astra
2. Attempt to launch a rocket

### Version

1.11.8

### Mod Loader Version

Fabric 0.14.10, Quilt 0.17.6

### Mod Loader

Fabric, Quilt

**Comment by AlexNijjar** [comment] 2022-12-11 04:41
Seems to be caused by this mixin https://github.com/fzzyhmstrs/kf/blob/master/src/main/java/me/fzzyhmstrs/keybind_fix/mixins/KeybindingMixin.java

I'll try fixing this by making Ad Astra's keybind click event get called before this is cancelled.

**Comment by AlexNijjar** [comment] 2022-12-11 08:03
should be fixed in the latest update. Tested it with keybind fix

**Closed as completed by AlexNijjar** 2022-12-11 08:03 UTC
Labels: bug

**Comment by jakeismyname** [comment] 2022-12-12 14:27
Yep, seems to work fine with Amecs as well on the latest CF release.
