### ISSUE TITLE
[Typo fix]: Typo in Solar Panel information

### ISSUE THREAD

**Issue by OracularSpy** [terrarium-earth/Ad-Astra#616] opened 2024-08-30 12:21 UTC
### Is your feature request related to a problem?

There exists a typo in the description of the Solar Panel
![image](https://github.com/user-attachments/assets/7a911b3b-8ad4-4cd0-99da-7105471a0248)

### Solution(s)

replace the incorrect "t" with a "y"

### Mod Version

ad_astra-forge-1.20.1-1.15.18

### Mod Loader Version

1.20.1 47.3.6

### Mod Loader

Forge

**Comment by ThatGravyBoat** [comment] 2024-12-10 17:02
Duplicate of https://github.com/terrarium-earth/Ad-Astra/issues/572

**Closed as completed by ThatGravyBoat** 2024-12-10 17:02 UTC
Labels: enhancement
