### ISSUE TITLE
[Bug]: Mapping Conflicts in Build Process

### ISSUE THREAD

**Issue by moritz-htk** [terrarium-earth/Ad-Astra#449] opened 2024-02-01 13:19 UTC
### Bug Description

I encountered a build failure while attempting to build my mod using Ad Astra version 1.16.1. The error is related to mapping conflicts during the remapping process, specifically in the `close` method of the `PlanetsScreen` class. The conflicts are marked as "unfixable", resulting in a failed build.

### How to Reproduce?

1. Create a new Fabric modding project using Fabric Loader 0.15.6, Fabric Loom 1.5.7 and Fabric API 0.95.4+1.20.4
3. Install Ad Astra (Fabric Version 1.16.1), Botarium (Fabric Version 3.0.7), Resourceful Config (Fabric Version 2.4.4) and Resourceful Lib (Fabric Version 2.4.6) in `build.gradle`
4. Run the build process using the standard build command

### Expected Behavior

The project should build successfully without any mapping conflicts, and the build output should indicate success.

### Version

1.16.1

### Mod Loader Version

1.20.4 - 0.15.6

### Mod Loader

Fabric

### Logs or additional context

```
> Configure project :
Fabric Loom: 1.5.7
Found existing cache lock file, rebuilding loom cache. This may have been caused by a failed or canceled build.
:remapping 56 mods from modImplementation (java-api)
Mapping target name conflicts detected:
  METHODs earth/terrarium/adastra/client/screens/PlanetsScreen/[net/minecraft/class_437/method_25419, close]()V -> close
There were unfixable conflicts.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'ad-astra-more-planets-fabric'.
> Failed to remap 56 mods

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

CONFIGURE FAILED in 58s
```

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment] 2024-02-01 20:24
Duplicate of #422 

As stated previously, I don't want to deal with mapping conflicts. Please use mojmap.

**Closed as not planned by AlexNijjar** 2024-02-01 20:24 UTC
Labels: bug
