### ISSUE TITLE
[Bug]: java.lang.IllegalStateException: Accidentally adding the same item stack twice [Станция зарядки] to a Creative Mode Tab: Ad Astra

### ISSUE THREAD

**Issue by ovrmiha** [terrarium-earth/Ad-Astra#646] opened 2024-11-10 15:14 UTC
### Bug Description

I have bug in Ad Astra. When I open my inventory in creative mode game crashing

### How to Reproduce?

1. Create new world
2. open inventory in creative mod
3. game crashing

### Version

1.15.18

### Mod Loader Version

1.20.1-fabric 0.16.9

### Mod Loader

Fabric

### Logs or additional context

[crash-2024-11-10_17.57.34-client.txt](https://github.com/user-attachments/files/17691914/crash-2024-11-10_17.57.34-client.txt)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment] 2024-12-10 16:57
Duplicate of https://github.com/terrarium-earth/Ad-Astra/issues/506

**Closed as completed by ThatGravyBoat** 2024-12-10 16:57 UTC
Labels: bug
