### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by G-Autizmo** [terrarium-earth/Ad-Astra#113] opened 2022-12-27 22:01 UTC
### Bug Description

When reaching Space, the UI breaks and prevents me from doing anything. I can't even press Esc to back out, it's fully stuck. I've even reset the server i've been playing on, no dice.
![image (2)](https://user-images.githubusercontent.com/121522245/209726080-89fd098e-94e8-4fd2-ab84-243780006259.png)

### Version

1.19.2

### Mod Loader Version

43.2.0

### Mod Loader

Forge

**Comment by AlexNijjar** [comment] 2022-12-27 22:15
Does it happen with just ad Astra and its dependencies installed? Or what pack are you using? This has been happening to a few people and it's been extremely difficult to diagnose as i can't reproduce it

**Comment by AlexNijjar** [comment] 2023-01-07 23:54
It's fixed in the latest version

**Closed as completed by AlexNijjar** 2023-01-07 23:54 UTC
Labels: bug
