### ISSUE TITLE
[Bug]: Forge 1.19.2  Crash

### ISSUE THREAD

**Issue by SirYeetusThe2nd** [terrarium-earth/Ad-Astra#147] opened 2023-01-14 19:49 UTC
### Bug Description

Whenever I try to launch Ad Astra on the Minecraft launcher, it immediately crashes and says unknown reason for crash. The exit code is 1

### Version

1.12.2

### Mod Loader Version

1.19.2-43.1.1

### Mod Loader

Forge

**Comment by AlexNijjar** [comment] 2023-01-15 02:47
can you send the latest.log

**Comment by Omig12** [comment] 2023-01-16 15:53
### I'm having the same issue.

Ad-astra! info:
`ad_astra-forge-1.19.2-1.12.2.jar`

On the server side: 

The only log entry that is marked as ERROR.
```sh
[10:47:39] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
        Mod ID: 'resourcefullib', Requested by: 'ad_astra', Expected range: '[1.1.19,)', Actual version: '[MISSING]'
        Mod ID: 'botarium', Requested by: 'ad_astra', Expected range: '[1.8.2,)', Actual version: '[MISSING]'
        Mod ID: 'resourcefulconfig', Requested by: 'ad_astra', Expected range: '[1.0.17,)', Actual version: '[MISSING]'
[10:47:41] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
```

Java Info: 
```sh
java version "17.0.5" 2022-10-18 LTS
Java(TM) SE Runtime Environment (build 17.0.5+9-LTS-191)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)
```

Forge Server Info: 
`forge-1.19.2-43.2.0-installer.jar`

The crash generates no additional logs on the server side.

---------------------------------

On the client side: 

![image](https://user-images.githubusercontent.com/6131141/212719270-a9ca5962-fcf4-4add-a427-b36e58423d86.png)

**Comment by AlexNijjar** [comment] 2023-01-16 15:58
your server side log tells you exactly what the issue is. You're missing Ad Astra's required dependencies

https://www.curseforge.com/minecraft/mc-mods/ad-astra/files/4337383

<img width="623" alt="Screenshot 2023-01-16 at 9 58 05 AM" src="https://user-images.githubusercontent.com/61668546/212720215-84c93951-0b62-4375-845c-ea71ba55d56f.png">

**Comment by Omig12** [comment] 2023-01-16 16:25
> your server side log tells you exactly what the issue is. You're missing Ad Astra's required dependencies
> 
> https://www.curseforge.com/minecraft/mc-mods/ad-astra/files/4337383
> 
> <img alt="Screenshot 2023-01-16 at 9 58 05 AM" width="623" src="https://user-images.githubusercontent.com/61668546/212720215-84c93951-0b62-4375-845c-ea71ba55d56f.png">

Great thanks! It would be cool to have that stated in the [Forge](https://www.curseforge.com/minecraft/mc-mods/ad-astra) description.

**Comment by AlexNijjar** [comment] 2023-03-02 18:31
it is

**Closed as completed** 2023-03-02 18:31 UTC
Labels: bug

**Comment by MightyPrigon** [comment] 2023-06-25 19:55
I actually have the same problem but I already have the additional mods that are needed. However it still doesn't launches.
Here is the launcher log:
[launcher_log.txt](https://github.com/terrarium-earth/Ad-Astra/files/11860676/launcher_log.txt)

**Comment by AlexNijjar** [comment] 2023-06-25 20:09
Can you send the latest.log? the launcher log won’t have the crash report

**Comment by MightyPrigon** [comment] 2023-06-25 20:25
[latest.log](https://github.com/terrarium-earth/Ad-Astra/files/11860733/latest.log)

Is it this one?

**Comment by AlexNijjar** [comment] 2023-06-25 20:50
Seems to be pretty much empty. send your modlist, maybe you accidentally installed one with for the  incorrect loader

**Comment by MightyPrigon** [comment] 2023-06-26 07:52
well it all started when i tried to launch the Ad Astra mod and I don't even have any mods in the normal minecraft mods folder right now. So these are the mods which are in the folder of the Ad Astra mod:

![Screenshot (36)](https://github.com/terrarium-earth/Ad-Astra/assets/132709151/dd993fb6-0adb-49d8-9b61-fe0702968046)

and this is the latest log from the time when I launched Ad Astra:

[latest.log](https://github.com/terrarium-earth/Ad-Astra/files/11865755/latest.log)

**Comment by munchir** [comment] 2023-07-12 19:21
hi i have been having the same problem as these guys and i have tried alot of things shuch as reinstalling forge reinstalling ad astra. renaming the files downloading the mod requirements and every time i try to fix it it just keeps crashing over and over
and i am getting very frustrated and desprate

**Comment by Toenut** [comment] 2023-08-29 12:11
hello, i have the exact same issue as mightyprigon.

**Comment by ChaosInsurgency951** [comment] 2023-12-14 16:25
same, log: https://pastebin.com/08tW41XF 

this is on tlauncher (cause im poor) and forge version 1.19.2, it seems to be only this version
