### ISSUE TITLE
[1.20.1] [Bug]: Fuel Refinery has 2 categories in REI

### ISSUE THREAD

**Issue by vizthex123** [terrarium-earth/Ad-Astra#557] opened 2024-05-19 20:34 UTC
### Bug Description

It shows up twice with different IDs, and slightly different designs between the two.

This one is labelled as "refining"
![image](https://github.com/terrarium-earth/Ad-Astra/assets/31721920/6aff21ed-8bda-43f9-a1ae-4efd032ee903)

And this one is labelled as "fuel refining"
![image](https://github.com/terrarium-earth/Ad-Astra/assets/31721920/51213885-9c72-4823-82f9-87236c59cef2)

Looking up the recipe for Ad Astra's fuel opens the one labelled "fuel refining".

I also noticed that a lot of recipe UIs show 2 copies of the block they're made in for whatever reason.

### How to Reproduce?

1) Install REI
2) Check the recipe for fuel

### Expected Behavior

Having only 1 tab for Fuel Refinery recipes

### Version

1.15.18

### Mod Loader Version

47.2.6

### Mod Loader

Forge

### Logs or additional context

https://gist.github.com/vizthex123/82a50766e2ca42261bf3c3a35e81802d

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment] 2024-05-31 01:01
This is most likely caused by REI's JEI compatabilty. Because it seems that you have both installed. This issue has been fixed in [dev](https://github.com/terrarium-earth/Ad-Astra/pull/533) and will release soon.

**Closed as completed by AlexNijjar** 2024-05-31 01:01 UTC
Labels: bug

**Comment by vizthex123** [comment] 2024-05-31 20:01
noice, thanks. I only have REI installed (why would anyone use 2 item viewer mods lol)

**Comment by AlexNijjar** [comment] 2024-05-31 20:07
I'd assumed you had both installed because the refining ID for JEI is "refining" and the ID on REI is "fuel_refining". But it may just be REI messing with the JEI compatabilty. Here's a compiled dev jar if you'd like to confirm that it works
[ad_astra-forge-1.20.1-1.15.19.jar.zip](https://github.com/user-attachments/files/15518290/ad_astra-forge-1.20.1-1.15.19.jar.zip)

**Comment by vizthex123** [comment] 2024-06-03 01:10
It's probably [REIPC](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items-hacks) causing that.

Checked the version you attached, and it's been fixed. Only loads the REI plugin.
