### ISSUE TITLE
[Bug]: Еhrown out of the lander (1.19.2)

### ISSUE THREAD

**Issue by SilinVeredno** [terrarium-earth/Ad-Astra#556] opened 2024-05-18 11:27 UTC
### Bug Description

I tested in creative mode and survival mode, on the Forge version. Wherever I land, I constantly appear on another planet behind the lander. (I didn’t squat the whole way).

P.S: forgive me for errors in the text, I use Google Transte. I wanted to find a discord server for reporting, but I came across your github :D
![image](https://github.com/terrarium-earth/Ad-Astra/assets/80191234/5b01d60d-1953-45a9-b0bd-eef6c2dbfe7b)
![image](https://github.com/terrarium-earth/Ad-Astra/assets/80191234/53a61ab4-9a2d-43c3-aa61-ea9ec3202321)
![image](https://github.com/terrarium-earth/Ad-Astra/assets/80191234/0bba80bf-fc47-4341-aac6-41d503580407)

### How to Reproduce?

when traveling to any planet/station/anywhere at all

### Version

1.12.7

### Mod Loader Version

1.19.2

### Mod Loader

Forge

### Code of Conduct

- [x] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by SilinVeredno** [comment] 2024-05-18 11:33
changed! I found why this happens
https://github.com/terrarium-earth/Ad-Astra/issues/319,
but how can I change this if I have already developed with this mod?

**Comment by AlexNijjar** [comment] 2024-05-31 00:41
Duplicate of #319. Please remove transit railway.

**Closed as not planned by AlexNijjar** 2024-05-31 00:41 UTC
Labels: bug
