### ISSUE TITLE
[Feature Request]: Keybind to Enable/Disable Jetsuit's Jetpack

### ISSUE THREAD

**Issue by v1-c705** [terrarium-earth/Ad-Astra#412] opened 2023-12-05 20:31 UTC
### Is your feature request related to a problem?

I'm always frustrated when I use a Jetsuit and have the jetpack kick in when I'm just trying to jump a block when walking.

### Solution(s)

Just add a keybind to disable and enable the Jetpack in the Jetsuit, please, pleease. I'm not even asking for hover mode.

### Describe alternatives you've considered

It's not a big deal to the point I think there might be an alternative to it.

### Mod Version

1.15.4

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment] 2023-12-11 21:31
duplicate of #213

**Closed as not planned by AlexNijjar** 2023-12-11 21:31 UTC
Labels: duplicate, enhancement
